name: Deploy Site to developer.multimokia.studio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install npm packages
        run: npm i

      - name: build static pages
        run: npm run build

      - name: SCP deploy action
        uses: nogsantos/ssh-scp-deploy@v1.3.0
        with:
          src: ./dist/*
          host: multimokia.studio
          user: ${{ secrets.SSH_USER }}
          remote: ${{ secrets.SSH_REMOTE_PATH }}
          key: ${{ secrets.IDENTITY }}
